language: generic
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $BUCKET
  skip_cleanup: true
  region: us-west-2
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|develop)$






